version: 2
updates:
  # Check for updates of all GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Check for updates of all Python packages
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
