version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - "pip install hatch"
    - "cd docs && hatch run build"
    - "mkdir _readthedocs"
    - "mv docs/site _readthedocs/html"

python:
  install:
    - method: pip
      path: .
