version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - "pip install hatch"
    - "cd docs && hatch run build"
    - "mkdir $READTHEDOCS_OUTPUT"
    - "mv docs/site $READTHEDOCS_OUTPUT/html"

python:
  install:
    - method: pip
      path: .
