version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - "pip install hatch"
    - "cd docs && bash -c 'hatch run build'"
    - "mkdir _readthedocs"
    - "mv docs/site _readthedocs/html"
#  jobs:
#    pre_build:
#      - "jupyter-book config sphinx docs/"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - hatch
#      extra_requirements:
#      - sphinx

#sphinx:
#  builder: html
#  fail_on_warning: false
