name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  pypi:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: |
          3.11

    - name: Add .local path
      run: |
        echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
        echo "PIPX_HOME=$HOME/.local/pipx" >> $GITHUB_ENV
        echo "PIPX_BIN_DIR=$HOME/.local/bin" >> $GITHUB_ENV

    - name: Install Base Dependencies
      run: |
        sudo apt-get install python3-venv pipx
        pipx install hatch

    - name: Build the package
      run: |
        hatch build

    - name: Publish the package
      run: |
        hatch publish --user __token__ --auth ${{ secrets.HATCH_INDEX_AUTH }}
